export const queryKeys = {
  catalogHome: ['catalog', 'home'] as const,
  families: ['catalog', 'families'] as const,
  products: (qs: string) => ['catalog', 'products', qs] as const,
  product: (slug: string) => ['catalog', 'product', slug] as const,
  productReviews: (slug: string) => ['catalog', 'reviews', slug] as const,
  productReviewEligibility: (slug: string) => ['catalog', 'reviews', slug, 'eligibility'] as const,
  cart: ['cart'] as const,
  wishlist: ['wishlist'] as const,
  addresses: ['addresses'] as const,
  orders: (page: number, status?: string) => ['orders', page, status] as const,
  order: (id: string) => ['order', id] as const,
  me: ['auth', 'me'] as const,
  adminDashboard: ['admin', 'dashboard'] as const,
  adminCovers: ['admin', 'covers'] as const,
  adminCoversPaged: (page: number) => ['admin', 'covers', 'paged', page] as const,
  adminFamilies: ['admin', 'families'] as const,
  adminFamiliesTable: (params: unknown) => ['admin', 'families', 'table', params] as const,
  adminCategoriesTable: (params: unknown) => ['admin', 'categories', 'table', params] as const,
  adminSubcategoriesTable: (params: unknown) => ['admin', 'subcategories', 'table', params] as const,
  adminProducts: (page: number) => ['admin', 'products', page] as const,
  adminInventory: ['admin', 'inventory'] as const,
  adminOrders: (page: number, status?: string) => ['admin', 'orders', page, status] as const,
  adminOrder: (id: string) => ['admin', 'order', id] as const,
  adminShipments: ['admin', 'shipments'] as const,
  adminDrivers: ['admin', 'drivers'] as const,
  adminUsers: (page: number, search?: string) => ['admin', 'users', page, search] as const,
  adminUser: (id: string) => ['admin', 'user', id] as const,
  driverShipments: ['driver', 'shipments'] as const,
};
